/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

  ==============================================================================
*/

#include "JuceHeader.h"
#include "MidiStochaster.h"
#include "MainAppWindow.h"
#include <vector>


//==============================================================================
class MiniMidiStochasterApplication  : public JUCEApplication {
    MainAppWindow* theMainWindow;
public:
    //==============================================================================
    MiniMidiStochasterApplication()
    {
    }

    ~MiniMidiStochasterApplication()
    {
    }

    //==============================================================================
    void initialise (const String& commandLine)
    {
        // Application's initialisation code
        theMainWindow = new MainAppWindow();
        theMainWindow->centreWithSize (400, 512);
        theMainWindow->setVisible (true);        
    }
    
    void shutdown()
    {
        // Do your application's shutdown code here..
        deleteAndZero(theMainWindow);
        
    }

    //==============================================================================
    void systemRequestedQuit()
    {
        quit();
    }

    //==============================================================================
    const String getApplicationName()
    {
        return "MelodyStochaster";
    }

    const String getApplicationVersion()
    {
        return ProjectInfo::versionString;
    }

    bool moreThanOneInstanceAllowed()
    {
        return true;
    }

    void anotherInstanceStarted (const String& commandLine)
    {
        
    }

private:
    
};

//==============================================================================
// This macro generates the main() routine that starts the app.
START_JUCE_APPLICATION(MiniMidiStochasterApplication)
